SBCode_WebPhone/Areas/Admin/Controllers/LoaiController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using SBCode_WebPhone.Data;
using SBCode_WebPhone.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SBCode_WebPhone.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class LoaiController : Controller
    {
        private readonly MyDBContext _dbcontext;
        private readonly ILogger _logger;

        public LoaiController(MyDBContext ctx, ILogger<LoaiController> logger)
        {
            _dbcontext = ctx;
            _logger = logger;
        }

       
        public IActionResult Index()
        {
            var data = _dbcontext.Loais.Include(lc => lc.LoaiCha).ToList();
            return View(data);
        }

        public IActionResult Create()
        {
            ViewBag.DanhSachLoaiCha = new LoaiDropDownVM(_dbcontext.Loais, "MaLoai", "TenLoai", "MaLoaiCha");

            return View();
        }

        [HttpPost]
        public IActionResult Create(Loai loai)
        {
            if (ModelState.IsValid)
            {
                _dbcontext.Add(loai);
                _dbcontext.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.DanhSachLoaiCha = new LoaiDropDownVM(_dbcontext.Loais, "MaLoai", "TenLoai", "MaLoaiCha");
            return View();
        }

        public IActionResult Edit(int id)
        {
            var ml = _dbcontext.Loais.FirstOrDefault(l => l.MaLoai == id);
            ViewBag.DanhSachLoaiCha = new LoaiDropDownVM(_dbcontext.Loais, "MaLoai", "TenLoai", "MaLoaiCha",ml.MaLoai);
            return View(ml);
        }

        [HttpPost]
        public IActionResult Edit(Loai loai)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var editloai = _dbcontext.Loais.FirstOrDefault(l => l.MaLoai == loai.MaLoai);
                    editloai.TenLoai = loai.TenLoai;
                    editloai.MoTa = loai.MoTa;
                    editloai.MaLoaiCha = loai.MaLoaiCha;
                    _dbcontext.Update(editloai);
                    _dbcontext.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    _logger.LogError(ex, $"Loi: {ex.Message}");

                    ViewBag.ThongBaoLoi = "Có lỗi";
                    ViewBag.DanhSachLoaiCha = new LoaiDropDownVM(_dbcontext.Loais, "MaLoai", "TenLoai", "MaLoaiCha");
                    return View();
                }
            }
            ViewBag.DanhSachLoaiCha = new LoaiDropDownVM(_dbcontext.Loais, "MaLoai", "TenLoai", "MaLoaiCha");
            return View();
        }

        public IActionResult Delete(int id)
        {
            try
            {
                var hh = _dbcontext.Loais.FirstOrDefault(h => h.MaLoai == id);
                _dbcontext.Remove(hh);
                _dbcontext.SaveChanges();
                return RedirectToAction("Index");

            }
            catch (Exception ex)
            {
                _logger.LogError(ex, $"Loi: {ex.Message}");
                ViewBag.ThongBaoLoi = "Có lỗi";
                return RedirectToAction("Index");

            }

        }
    }
}

SBCode_WebPhone/Controllers/HangHoaController.cs
using Microsoft.AspNetCore.Mvc;
using X.PagedList;
using SBCode_WebPhone.Data;
using SBCode_WebPhone.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace SBCode_WebPhone.Controllers
{
    public class HangHoaController : Controller
    {

        private readonly MyDBContext _dbcontext;

        public HangHoaController(MyDBContext ctx)
        {
            _dbcontext = ctx;

        }
        public IActionResult Index(int? mucloai, int? page, int? sapxep, string timkiem)
        {//Phan trang va lấy loại
            if (page == null) page = 1;
            int pageSize = 10;
            int pageNum = (page ?? 1);
            IList<Loai> dsLoai = _dbcontext.Loais.ToList();
            ViewData["dsLoai"] = dsLoai;
            ViewBag.mucloaihientai = mucloai;
            ViewBag.sapxep = sapxep;
            //SapXep
            List<HangHoaVM> dsHangHoa;
            List<HangHoa> data;
            //Tìm Kiếm
            if (timkiem != null && timkiem != "")
                data = _dbcontext.HangHoas.Where(p => p.TenHh.ToLower().Contains(timkiem.ToLower()) || p.Loai.TenLoai.ToLower().Contains(timkiem.ToLower()) || p.XuatXu.ToLower().Contains(timkiem.ToLower())).ToList();
            else
                data = _dbcontext.HangHoas.ToList();

            //Mục Loại
            if (mucloai.HasValue)
            {
                data = data.Where(l => l.MaLoai == mucloai || l.Loai.MaLoaiCha == mucloai).ToList();
            }
            dsHangHoa = data.Select(hh => new HangHoaVM
            {
                MaHh = hh.MaHangHoa,
                TenHh = hh.TenHh,
                DonGia = hh.DonGia,
                GiamGia = hh.GiamGia,
                Hinh = hh.Hinh,
                ThuongHieu = hh.ThuongHieu,
                XuatXu = hh.XuatXu,
                SoLuongBan = hh.SoluongBan,
                MoTa = hh.MoTa,
                SoLuong = hh.SoLuong,
                TenLoai = hh.Loai.TenLoai,
            }).ToList();


            dsHangHoa = SapXep(dsHangHoa,sapxep);

            return View(dsHangHoa.ToPagedList(pageNum, pageSize));
        }

        public List<HangHoaVM> SapXep(List<HangHoaVM> dsHangHoa, int? sapxep)
        {
            //SapXep
            if (sapxep == -1)
                return dsHangHoa.OrderByDescending(ds => ds.GiaBan).ToList();
            else if (sapxep == 0)
                return dsHangHoa.OrderBy(ds => ds.GiaBan).ToList();
            else if (sapxep == 1 || sapxep == 3)
                return dsHangHoa.OrderByDescending(ds => ds.SoLuongBan).ToList();
            else
                return dsHangHoa.ToList();
        }
        public IActionResult Detail(Guid id)
        {
            ViewBag.NoiGui = "Không Rõ";
            ViewBag.Tenadmin = "";
            var Admin = _dbcontext.UserRoles.FirstOrDefault(kh => kh.RoleId == 11).UserId;
            if (Admin != null)
            {
                ViewBag.NoiGui = _dbcontext.KhachHangs.FirstOrDefault(kh => kh.MaKh == Admin).DiaChi;
                ViewBag.Tenadmin = _dbcontext.KhachHangs.FirstOrDefault(kh => kh.MaKh == Admin).HoTen;
            }
            ViewBag.getdiachi = "Không Rõ";
            
            if((this.User.FindFirstValue(ClaimTypes.Email)) != null) { ViewBag.getdiachi = _dbcontext.KhachHangs.FirstOrDefault(kh => kh.Email == (this.User.FindFirstValue(ClaimTypes.Email))).DiaChi; }
            var HangHoa = _dbcontext.HangHoas
                .Include(hh=>hh.Loai)
                .Include(hh =>hh.Loai.LoaiCha)
                .FirstOrDefault(hh => hh.MaHangHoa == id);
            List<HangHoa> _4sanPhamCungLoai = _dbcontext.HangHoas.Where(a => a.MaHangHoa != id && a.MaLoai == HangHoa.MaLoai).Take(4).ToList();
            ViewData["spcungloai"] = _4sanPhamCungLoai;
            return View(HangHoa);
        }
      

    }
}

SBCode_WebPhone/Views/Shared/_Layout _Admin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SBCode_WebPhone</title>
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
    <link href="~/admin/css/styles.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-primary">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="index.html">SBCode_Admin</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        @*<form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
            </div>
        </form>*@
        <!-- Navbar-->
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-light bg-light" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Core</div>
                        <a class="nav-link" href ="HangHoa/Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Trở Lại Shop
                        </a>
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                            <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                            Pages
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                                    Authentication
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav">
                                        <a class="nav-link" href="~/startbootstrap-sb-admin-gh-pages/login.html">Login</a>
                                        <a class="nav-link" href="register.html">Register</a>
                                        <a class="nav-link" href="password.html">Forgot Password</a>
                                    </nav>
                                </div>
                            </nav>
                        </div>
                        <div class="sb-sidenav-menu-heading">Quản Lý</div>
                        <a class="nav-link" asp-action="Index" asp-controller="HangHoa">
                            <div class="sb-nav-link-icon"><i class="fab fa-product-hunt"></i></div>
                            Hàng Hóa
                        </a>
                        <a class="nav-link" asp-action="Index" asp-controller="Loai">
                            <div class="sb-nav-link-icon"><i class="fas fa-wrench"></i></div>
                            Loại
                        </a>
                        <a class="nav-link" asp-action="PhanQuyen" asp-controller="PhanQuyen">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Phân Quyền
                        </a>
                    </div>
                </div>
              </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid">
                    <h1 class="mt-4">@ViewBag.Title</h1>
                    @RenderSection("breadcrum", required: false)
                    <div class="card mb-4">
                        <div class="card-body">
                            @RenderBody()
                        </div>
                    </div>
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">SBCode-Shop 2021</div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
            crossorigin="anonymous"></script>
    <script src="~/admin/js/scripts.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
    <script src="~/admin/js/datatables-simple-demo.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

SBCode_WebPhone/Views/Shared/_Layout_GioHang.cshtml
@using SBCode_WebPhone.Helper
@using SBCode_WebPhone.ViewModels
@{ 

    var gioHang = Context.Session.Get<List<GioHangVM>>("GioHang");
    if (gioHang == null)
    {
        gioHang = new List<GioHangVM>();
    }
}
<div class="header__cart hide-on-mobile-tablet">
    <div class="header__cart-wrap">
        <i class="header__cart-icon fas fa-shopping-cart"></i>
        <span class="header__cart-wrap-notice">@gioHang.Sum(p => p.SoLuong)</span>

        <!-- No cart: Header__cart-list--no-cart -->

        <div class="header__cart-list header__cart-list--no-cart">
            @if (gioHang.Count == 0)
            {
                <img src="~/images/no-cart.png" class="header__cart-no-card-img" />
                <span class="header__cart-list-no-card-msg">
                    Chưa có sản phẩm
                </span>
            }
            else
            {
                <div class="header__cart-heading">Sản phẩm đã thêm</div>

                <!-- Cart item -->
                @foreach (var item in gioHang)
                {
                        <a asp-action="Detail" asp-route-id="@item.MaHangHoa" asp-controller="HangHoa"> <ul  class="header__cart-list-item">
                                <li class="header__cart-item">
                                    <div class="header__cart-img-wrapper">
                                        <a asp-action="Detail" asp-route-id="@item.MaHangHoa" asp-controller="HangHoa"><img  src="~/Hinh/HangHoa/@item.Hinh"
                                             class="header__cart-img"></a>
                                    </div>
                                        <a asp-action="Detail" asp-route-id="@item.MaHangHoa" asp-controller="HangHoa">  <div  class="header__cart-item-info">
                                        <div class="header__cart-item-head">
                                            <div class="header__cart-item-name">
                                                @item.TenHh
                                            </div>
                                            <div class="header__cart-item-price-wrap">
                                                <span class="header__cart-item-price">@item.GiaBan.ToVnd()</span>
                                                <span class="header__cart-item-multiply">x</span>
                                                <span class="header__cart-item-qnt">@item.SoLuong</span>
                                            </div>
                                        </div>
                                        <div class="header__cart-item-body">
                                            <span class="header__cart-item-description">

                                            </span>
                                            <span class="header__cart-item-remove">@Html.ActionLink("Xóa", "RemoveCartItem", "GioHang", new { id = item.MaHangHoa })</span>
                                        </div>
                                    </div>
                                    </a>
                                </li>
                            </ul>
                          </a>
                 }


                    <button class="header__cart-view-cart btn btn--primary" onClick="location.href='/GioHang'">Xem giỏ hàng</button>
                }
            </div>
    </div>
</div>